### ISSUE TITLE
CSS variable documentation out of step with latest release

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-tile#2]
Hi @neovichsu,

Can you update the following comment block in the component to match the new CSS variables that you added in the last PR?

https://github.com/PredixDev/px-tile/blob/master/px-tile.html#L28

A new PR would be great! Thanks.

**Comment by neovichsu** [comment]
@mdwragg 
I don't see any discrepancy between the CSS variable wit latest CSS used in px tile. if possible, could you point out where?

Thanks,

**Comment by mdwragg** [comment]
`--px-tile-text-height` for one!

**Comment by neovichsu** [comment]
Thanks! I see it now.

**Comment by mdwragg** [comment]
Fixed by #4
